# Generated by Django 4.2.3 on 2023-11-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/sunglass')),
            ],
        ),
    ]
