# Generated by Django 4.2.7 on 2023-12-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cartt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartt',
        ),
        migrations.DeleteModel(
            name='productdet',
        ),
    ]
