# Generated by Django 4.2.7 on 2023-12-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_cartt_delete_productdet'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('productid', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('a', 'eyeglass men'), ('b', 'eyeglass women'), ('c', 'eyeglass kids'), ('d', 'sunglass men'), ('e', 'sunglass women'), ('f', 'sunglass kids'), ('g', 'computer glass')], default='a', max_length=100)),
                ('image', models.ImageField(upload_to='images/sunglass')),
            ],
        ),
    ]
