# Generated by Django 4.2.6 on 2023-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cartt_productdet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartt',
            name='productid',
            field=models.IntegerField(),
        ),
    ]
