# Generated by Django 5.0 on 2023-12-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartt',
        ),
    ]
