# Generated by Django 4.2.7 on 2023-12-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_mycart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mycart',
        ),
    ]
