# Generated by Django 4.2.7 on 2023-12-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productdet')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usignup')),
            ],
        ),
    ]
