# Generated by Django 4.1.7 on 2024-01-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_wish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mycart',
        ),
    ]
