# Generated by Django 4.1.7 on 2024-01-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_wish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usignup',
        ),
    ]
